version: '2.4'

services:
  proxy:
    build: .
    tty: true
    devices:
      - /dev/net/tun:/dev/net/tun
      - /dev/ppp:/dev/ppp
    cap_add:
      - NET_ADMIN

    ports:
      - 8118:8888

    environment:
      - TINYPROXY_PASSWORD=Passw0rd
      - FORTI_HOST=vpn.forti.com
