version: '2.4'

services:
  proxy:
    build: .
    tty: true
    volumes:
      - ./data:/data:ro
    devices:
      - /dev/net/tun:/dev/net/tun
      - /dev/ppp:/dev/ppp
    cap_add:
      - NET_ADMIN

    ports:
      - 8118:3128
      - 1080:1080
